[package]
name = "krilla-svg"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tiny-skia-path = { workspace = true }
zune-png = { workspace = true }
krilla = { workspace = true }
usvg = { workspace = true }
tiny-skia = { workspace = true }
resvg = { workspace = true }
fontdb = { workspace = true }
